interruptions.html.md.erb

- Based on work from: https://www.pivotaltracker.com/story/show/154128739

Add events that interrupt service page

---

installing-nsx-t.html.md.erb
ports-protocols-nsx-t.html.md.erb

Please insert into the TOC schema for NST-T.

Add new firewall ports topic and xref from NSX-T instructions. 

---

aws-om-deploy.html.md.erb
aws-prepare-env.html.md.erb
aws-requirements.html.md.erb
aws.html.md.erb
index.html.md.erb
installing-pks-aws.html.md.erb

Have update the documentation for AWS. 
On the configuring AWS page I have left out the Load Balancer configuration as that is something I haven't investigate yet and would like to leave until I have a fully build tile.
[#155365382]

Update documentation for AWS

---

access-dashboard.html.md.erb
configure-tiller-helm.html.md.erb
deploy-workloads.html.md.erb
diagnostic-tools.html.md.erb
gcp-om-config.html.md.erb
gcp-om-deploy.html.md.erb
gcp-prepare-env.html.md.erb
helm.html.md.erb
installing-nsx-t.html.md.erb
installing-pks-gcp.html.md.erb
installing-pks-vsphere.html.md.erb
interruptions.html.md.erb
troubleshoot-issues.html.md.erb
upgrade-pipeline.html.md.erb
upgrade-pks.html.md.erb
using.html.md.erb
volumes.html.md.erb
vsphere-om-config.html.md.erb

Melinda, I'll do a second round of copy edits (per our conversation) after you've had the chance to review / commit these changes.

Style copy edits for cross-references and one fix to PKS link.

---

installing-pks-aws.html.md.erb

Add documentation for creating LB for PKS API on AWS

---

_login-pks-api.html.md.erb

Reverts pivotal-cf/docs-pks#194

Revert "Update pointer to login topic."

---

deploy-workloads.html.md.erb

This are additional steps that are required to setup a load balancer on aws. We are not sure where to put them
[#157145705]
Signed-off-by: Angela Chin <achin@pivotal.io>

AWS specific steps to setup a load balancer on the workloads

---

manage-users.html.md.erb

@mnagle1 Here is the PR for Tracker https://www.pivotaltracker.com/story/show/156162188

Mention Unknown key warning message is safe to ignore.  Story 156162188

---

deploy-workloads.html.md.erb

https://www.pivotaltracker.com/story/show/157145705
[#157145705]

Being more specific about key and value

---

vsphere-prepare-env.html.md.erb

@mfine30 @st3v @mjgutermuth The worker account shouldn't have additional storage permissions.

vSphere worker shouldn't be granted any storage permissions.

---

installing-pks-aws.html.md.erb
installing-pks-gcp.html.md.erb
installing-pks-vsphere.html.md.erb

Let us know if there are any issues!
[#156847665]
Signed-off-by: Angela Chin <achin@pivotal.io>

Add documentation for setting number of master/etcd instances

---

maintain-uptime.html.md.erb

[#155895911]
We are not 100% sure where to position this documentation, we are open to suggestion where to move it
Signed-off-by: Olena Pleshan <opleshan@pivotal.io>

Documentation about multi-azs

---

diagnostic-tools.html.md.erb

Typo for /var/

---

gcp-cluster-load-balancer.html.md.erb
release-notes.html.md.erb

[#158004127]
Signed-off-by: Nikita Rathi <nrathi@pivotal.io>

Adding warning for recreation of vms and load balancers

---

release-notes.html.md.erb

[#158004847]
Signed-off-by: Olena Pleshan <opleshan@pivotal.io>

Add CLI timeout issue into Known Issues

---

release-notes.html.md.erb
vsphere-requirements.html.md.erb

Remove NSX-T 2.2 and vSphere 6.7 from PKS 1.1 supported configurations

---

installing-nsx-t.html.md.erb
installing-pks.html.md.erb

This merge broke our builds -- I'm going to pull the branch locally and investigate

Revert " Update vRLi, Wavefront, and Networking tab in PKS tile."

---

manage-users.html.md.erb

Changes as suggested in #158530303

Better LDAP DN example for Administrators Group

---

manage-users.html.md.erb

If should be Control Plane not `Pane`

Change `pane` to `plane`

---

access-dashboard.html.md.erb

[#158389496]
Story link in OD-PKS backlog for context: https://www.pivotaltracker.com/story/show/158389496

Simplify accessing the dashboard instructions.

---

installing-pks.html.md.erb

Adding additional minimum worker nodes for multi az

---

release-notes.html.md.erb

Added known issue on upgrading #158632463

---

release-notes.html.md.erb

Let us know if you have any questions. We added additional release notes based on CFCR release notes and an overview of our backlog.
Also added a Bug Fixes section to release notes.
[#158720635]
Signed-off-by: Angela Chin <achin@pivotal.io>

Completed release notes for v1.1.0

---

gcp-om-config.html.md.erb
vsphere-om-config.html.md.erb

[#158440485]
Story link for context: https://www.pivotaltracker.com/story/show/158440485
Signed-off-by: Ben Chapman <bchapman@pivotal.io>

Add note for what cidrs to avoid for services network

---

installing-nsx-t.html.md.erb

Story link for context: https://www.pivotaltracker.com/story/show/158440485
[#158440485]

Update NSX docs to also note k8s services reserved cidr

---

installing-pks.html.md.erb

Story for context: https://www.pivotaltracker.com/story/show/158904932
[#158904932]

Note that only `user@domain` is supported for vSphere master creds

---

installing-pks.html.md.erb

Story for context: https://www.pivotaltracker.com/story/show/158904932
[#158904932]

Note that only `user@domain` is supported for vSphere master and worker

---

installing-pks-cli.html.md.erb

Story for context: https://www.pivotaltracker.com/story/show/158810889
This will also be backported to the 1.0 docs
[#158810889]

Add documentation about the PKS_HOME env var

---

concepts.html.md.erb
installing-pks.html.md.erb
vm-sizing.html.md.erb

* Information about sizing masters and worker nodes
[#153595373]
Signed-off-by: Brendan Nolan <bnolan@pivotal.io>

Create new page with recommendations of VM sizing

---

vsphere-requirements.html.md.erb

Added resource documentation for planning ephemeral compilation & errand VM capacity

Added data for capacity planning of ephemeral VMs

---

upgrade-pks.html.md.erb

@outofmem0ry Let me know if we need more than this. thanks

Addresses Issue 281

---

troubleshoot-issues.html.md.erb

Troubleshooting step for PKS with NSXT upgrade failure

---

aws-prepare-env.html.md.erb

Includes space-fix for issue #313

Docs pks issue 311 and 313

---

release-notes.html.md.erb

@animatedmax @mjgutermuth -- Still WIP, waiting for final ok from Anish, Michael, etc.

Adding Known Issues to 115 RNs

---

_uaa.html.md.erb
manage-users.html.md.erb

Hi @kdolor-pivotal you should be just able to merge this to continue the work.
[#160167870]
Signed-off-by: Fabio Mangione <fmangione@pivotal.io>

Adding documentation for using groups

---

_uaa.html.md.erb
manage-users.html.md.erb

[#159932914]
Signed-off-by: Nikita Rathi <nrathi@pivotal.io>

Add documentation for Naomi's OIDC flow

---

_pas-and-pks.html.md.erb

Called out that they should always seperate

[Updated] Separate OMs

---

volumes.html.md.erb

Adding AWS storage class

---

vsphere-nsxt-requirements.html.md.erb

See https://www.pivotaltracker.com/story/show/160598605

Adds NSX-T 2.2 support for vSphere with NSX-T

---

_plans.html.md.erb

[#159070549]
Signed-off-by: Fabio Mangione <fmangione@pivotal.io>

Adding Maximum number of workers field

---

release-notes.html.md.erb

Notes complete for OD-PKS, Networking and Oratos not updated

Updated release notes for 1.2.

---

about-lb.html.md.erb
cli/index.html.md.erb
network-profiles.html.md.erb

WIP -- Network profiles documentation for PKS 1.2. This is just the CLI commands. Will be adding more today and tomorrow.

Network Profiles documentation

---

aws-prepare-env.html.md.erb

[#160786916]
Signed-off-by: Neil Hickey <nhickey@pivotal.io>

Adding new way to add passrole to the user

---

aws-cluster-load-balancer.html.md.erb

[#160788658]
Equivalent [page of GCP load balancer](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/gcp-cluster-load-balancer.html) for AWS.
Signed-off-by: Greg Patricio <gpatricio@pivotal.io>

Docs for LB in AWS

---

cli/index.html.md.erb

PKS 1.2 cli updates

---

release-notes.html.md.erb

Updating language for known issue re: network profiles

---

nsxt-prepare-env.html.md.erb

This applies to 1.1 only (already addressed in 1.2)

Remove service ls

---

configuring-pvs.html.md.erb
installing-nsx-t.html.md.erb
network-profiles.html.md.erb
vsphere-persistent-storage.html.md.erb

For the 1.2 branch, and master. thanks

Pvs nsxt edits

---

network-profiles.html.md.erb

New feature for 1.2.1, only applies to master, thanks

121 routable pods

---

generate-nsx-ca-cert.html.md.erb

This applies to the 1.2, 1.2.1, and master branches. Thanks.

Fix bugs with Reg NSX CA Cert instructions

---

release-notes.html.md.erb

Added RN for routable pods, and placeholder content for other 1.2.1 stuff

Adding draft of 1.2.1 release notes

---

access-dashboard.html.md.erb

The content on the end page is the same

PKS 1.2 uses Kubernetes 1.11

---

troubleshoot-issues.html.md.erb
vm-sizing.html.md.erb

This PR applies to 1.2.0, 1.2.1 and master. thanks

Troubleshooting updates

---

_plans.html.md.erb

I tried to make a `Note` based on other occurrences of Notes, but I'm not sure how it will look when its rendered on the page. This text change may need to be modified to make sure the styling is correct.

Add note about clusters with more than 200 workers

---

installing-nsx-t.html.md.erb
installing-pks-aws.html.md.erb
installing-pks-gcp.html.md.erb
installing-pks-vsphere.html.md.erb
release-notes.html.md.erb

Also applies to master and 1.2.1

Added warning to all PKS tile installation sections and RNs

---

vsphere-om-config.html.md.erb

Applies to 1.2 branch and master branch.
Tracker: https://www.pivotaltracker.com/story/show/161649859
More substantial fix to this topic is WIP

Fix for #161649859

---

vm-sizing.html.md.erb

PKS 1.2.1 removed the worker max of 50. I don't believe there is a documented maximum anymore.

Update max worker statement

---

istio-on-pks.html.md.erb

Feedback from Dev, should be good to go for staging. Thanks.

Updates from dev

---

network-profiles.html.md.erb
nsxt-topologies.html.md.erb

Applies to the v1.2.3 release. Content is already updated in the master branch. thanks

123 large lb

---

vsphere-nsxt-om-config.html.md.erb
vsphere-om-config.html.md.erb

Addresses this issue: https://github.com/pivotal-cf/docs-pks/issues/293. 
Also applies to 1.3/master branch. 
thanks

Addresses the 'Director Hostname #293' issue

---

network-profiles.html.md.erb

This only applies to 1.2 branch. It it already included in Master (or will be soon). thanks

Adding Pods Subnet Prefix for 1.2.3

---

ports-protocols-nsx-t.html.md.erb

Should be type:LoadBalancer not type: LoadBalancerServices

Fixed type: LoadBalancer

---

network-profiles.html.md.erb

For 1.2.4 branch. Already in Master. thanks

Adding new version of using net profiles

---

release-notes.html.md.erb

Please merge and deploy. Thanks.

Updates to 124 RNs

---

network-profiles-define.html.md.erb

This PR applies to the 1.2 docs and master. Thanks.

Update network profiles params

---

delete-cluster.html.md.erb
release-notes.html.md.erb

Applies to 1.2 and 1.3/master branches. Out for review. Thanks.

Adding failed cluster deletion steps and known issue for 1.2

---

_plans.html.md.erb

As discussed in slack we created a PR being more specific about az on azure

Update documentation about az on azure

---

proxies.html.md.erb

Applies to 1.2 branch and master, thanks

Add PKS and Harbor hostnames to No Proxy -- from feedback

---

nsxt-multi-pks.html.md.erb

Applies to the master and 1.2 branches. thanks

Updates from feedback

---

release-notes.html.md.erb

See https://pivotal-spike.atlassian.net/browse/PKS-49

Updating 1.2 RNs with known issue

---

release-notes.html.md.erb

Ryan Jones & Merlin Glynn Reviewed Release notes

Update 1.2.5 Release Notes in 1.2.5 Branch

---

release-notes.html.md.erb

Adjusted 1.2.5 Whats New for UAA SAML Cert
Added Known Issues for 1.2.4 & 1.2.5

PKS 1.2.6 Release Notes

---

release-notes.html.md.erb

Resolved 2 known issues for Invalid Cert Trust & VM Types

Updated release notes:

---

azure-managed-identities.html.md.erb

Per discussion with @bentarnoff . I am submitting this PR for issue 507

Issue 507: making the 2 changes

---

nsxt-deploy.html.md.erb
nsxt-prepare-env.html.md.erb

Applies to the master/1.3 branch. Thanks.

Updates to formatting and nsx-t load balancer support

---

nsxt-multi-t0.html.md.erb
release-notes.html.md.erb
vsphere-nsxt-requirements.html.md.erb

Applies to the master/1.3 branch.

Updates to supported NSX-T versions

---

release-notes.html.md.erb

PM wants all network profile features rolled into 1.3 listed in the RNs

Adding other network profile features rolled up in 1.3

---

index.html.md.erb

Update table to indicate Harbor can be used with PKS on GCP and AWS

---

network-profiles-define.html.md.erb

MT0 json needs brackets around fip and block ids

---

index.html.md.erb

Addresses https://github.com/pivotal-cf/docs-pks/issues/523 for PKS 1.2 branch.

Update table to show support for Harbor for 1.2

---

network-profiles-define.html.md.erb

Adding FIP clarification if multiple for 1.2

---

network-profiles-define.html.md.erb

Add clarfication about 2 FIP IDs for 1.4

---

vsphere-nsxt-requirements.html.md.erb
vsphere-requirements.html.md.erb

Immediate need is to apply this to the 1.3 branch and deploy to production because someone reported this as missing; verified with the vmware interop matrix; also applies to 1.4/master, thanks

Adding vSphere 6.7 u1 for PKS 1.3

---

vsphere-nsxt-rpd-mpd.html.md.erb

Applies to 1.4/master as well. Ideally would also be ported to the 1.2 branch. Thanks.

Adding note about MPD

---

volumes.html.md.erb
vsphere-persistent-storage.html.md.erb

Applies to 1.3 and 1.4/master. Thanks

Final updates from feedback

---

create-cluster.html.md.erb
delete-cluster.html.md.erb
troubleshoot-issues.html.md.erb
vsphere-nsxt-cluster-objects.html.md.erb
vsphere-nsxt-index.html.md.erb

Addresses https://www.pivotaltracker.com/story/show/163532437.

Creating deleting clusters

---

release-notes.html.md.erb

Release notes from PM for 1.2.7 & 1.2.8

1.2.7 1.2.8 rn

---

release-notes.html.md.erb

1.3.1 release notes: Added known issues from 1.3.0 that have not yet …

1.3 Release Notes Update

---

index.html.md.erb

applies to 1.3 and master, thanks

Update Harbor support for Azure

---

network-profiles-define.html.md.erb

Important fix. Thanks. Will do one for 1.2.x as well.

Fix pod_routable example

---

network-profiles-define.html.md.erb

Fix pod_routable type

---

release-notes.html.md.erb

Important merge and deploy please. Thanks.

Fixing upgrade path to 1.2.7

---

_plans.html.md.erb
vm-sizing.html.md.erb

Applies to 1.3 and 1.4/master branches. Thanks.

Adding reference to OM API for worker VM customizations

---

upgrade-pks-nsxt.html.md.erb

fix links in 1.2 upgrade pks w/ nsx-t since 1.1 is now PDF links won't work anymore

Fixing links

---

_plans.html.md.erb
vm-sizing.html.md.erb

Applies to 1.3 and 1.4/master. Thanks.

Updating for master node customization

---

network-profiles-define.html.md.erb

Applies to 1.3.4 and 1.4/master. Thanks.

Network profiles nodes_dns feature

---

nsxt-multi-t0.html.md.erb

Hi @lparis. I added only textual changes to this PR. If the changes look good, I'll add a couple of screenshots as well. Let me know when you review the PR and I'll merge it into the main branch.

Add more details [#164025102]

---

_plans.html.md.erb

also applies to 1.4/master, based on PM decision, thanks

Removing mention of max worker nodes per PM

---

_plans.html.md.erb

Added documentation about two fields `Kubelet customization - system-reserved` and `Kubelet customization - eviction-hard` in the plans page. Please refer to the [tracker story](https://www.pivotaltracker.com/story/show/164150613) for more information.

Added documentation for kubelet customization on the plans page.

---

volumes.html.md.erb

Applies to 1.3 and master/1.4. Feedback from Slack discussion: https://pivotal.slack.com/archives/C3D106JLR/p1553022839213600?thread_ts=1553020254.210300&cid=C3D106JLR

Add SSH prereq operation for static PVs

---

ports-protocols-nsx-t.html.md.erb

Applies to 1.3 and master/1.4, based on feedback from the field. Thanks.

Updates to ports and protocols for NSXT: 2 removals, 1 addition

---

nsxt-deploy.html.md.erb
nsxt-prepare-env.html.md.erb
vsphere-nsxt-rpd-mpd.html.md.erb

Updates based on user feedback. Changes also apply to master/1.4. Thanks.

Fix some issues reported by users

---

_cloud-provider.html.md.erb

https://www.pivotaltracker.com/story/show/163262199
Applies to 1.3 and master/1.4
thanks

Addresses #163262199

---

network-profiles-define.html.md.erb
network-profiles.html.md.erb

https://www.pivotaltracker.com/story/show/164817683.

Adding documentation for update-cluster --network-profile

---

upgrade-pks-nsxt-24.html.md.erb

Link fixes and other cleanup to the PKS 1.3.6 / NSX-T 2.4 upgrade topic.

Updates to URLs

---

_increase_persistent_disk.html.md.erb
aws-requirements.html.md.erb
azure-requirements.html.md.erb
gcp-requirements.html.md.erb
troubleshoot-issues.html.md.erb
vsphere-nsxt-rpd-mpd.html.md.erb
vsphere-requirements.html.md.erb

- Add a recommend disk size guideline based on number of running pods
- Add the partial to the main resource requirements of specific
IaaS
- Create a section in troubleshooting if user encounter login issues
caused by full persistent disk
Co-authored-by: Fei Yang <fyang@pivotal.io>
Co-authored-by: Laura Squire <brinduc@gmail.com>

Add snippets for increasing persistent disk size

---

upgrade-pks-nsxt-24.html.md.erb

Please merge and deploy, thanks

Crucial fix

---

release-notes.html.md.erb

https://www.pivotaltracker.com/story/show/163424345

Azure rg known issue

---

generate-nsx-ca-cert.html.md.erb

Fix applies to the 1.3 and the master/1.4 branches. Thanks.

Fix statement to make it more accurate

---

_plans.html.md.erb
admission-plugins.html.md.erb
deny-escalating-execution.html.md.erb
security-context-deny.html.md.erb
upgrade-pks-nsxt.html.md.erb
vsphere-host-group.html.md.erb

Additional feedback and fixes, thanks

Misc feedback

---

checklist.html.md.erb
pod-security-policy.html.md.erb

Psp updates

---

release-notes.html.md.erb

Updating the stemcell from v170.15 to 250.25 per check with Davis.

Stemcell version update

---

generate-nsx-ca-cert.html.md.erb
upgrade-pks-nsxt.html.md.erb

Updates to the NSX upgrade steps for PKS 1.4 with NSX-T 2.4

Pks upgrade

---

release-notes.html.md.erb
upgrade-pks-nsxt-24.html.md.erb

Please merge and deploy. Thanks.

Important fixes to the 1.3 docs

---

admission-plugins.html.md.erb
checklist.html.md.erb
deny-escalating-execution.html.md.erb
pod-security-policy.html.md.erb

updates docs to reflect new default behavior

Update admission plugin

---

manage-users.html.md.erb

Request from Merlin. Sent for his review.

Feedback on get-kubeconfig for 1.4

---

nsxt-deploy.html.md.erb

Explanation for step in HA VIP NSX Edge

---

pod-security-policy.html.md.erb

Fix formatting

---

_vsphere_versions.html.md.erb

also applies to master, thanks

Adding vsphere v6.7 U2

---

_vsphere_versions.html.md.erb

This applies to 1.4 and master/1.5. Thanks.

Just reference the VMware Interop Matrix

---

index.html.md.erb

This fix also applies to the 1.3, 1.4, and 1.5/master branches. Thanks.

Fix broken link

---

nsxt-deploy-24.html.md.erb

This is a fairly critical update. Can we merge it so it goes onto staging for review? Thanks.

Adding pw expiration steps for NSXT 2.4

---

bbr-install.html.md.erb
bbr-restore.html.md.erb

This is a new pull request to continue the work of https://github.com/pivotal-cf/docs-pks/pull/668 
This addresses some comments we received from @ograves-pivotal 
@ograves-pivotal we did not have permission to push into your branch so I open PR against your branch.

Address comments for: Complete the Backup + Restore documentation for PKS

---

_usage-data.html.md.erb

`https://vcsa.vmware.com/ph-prd` ->  `https://vcsa.vmware.com/ph`
@kdudala1 We went ahead and made the change here.

Update telemetry endpoint

---

console/console-index.html.md.erb
console/console-troubleshooting.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/monitor-manage-console.html.md.erb
console/ova-deployment-prereqs.html.md.erb

These are the first topics for the Gear2 docs.
@lparis can you please take a look at the formatting and general style to make sure that they conform to the PKS standard?

First wave of topics for Gear2 docs

---

vsphere-index.html.md.erb
vsphere-om-install-config.html.md.erb
vsphere-prepare-env.html.md.erb

Feedback on vSphere without NSX-T docs from CRE team. Applies to the 1.4 and 1.5/master branches. Thanks.

Feedback changes

---

console/console-index.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/patch-console-components.html.md.erb
console/upgrade-console.html.md.erb

These are placeholders. Will fill out contents in later commits.
@animatedmax and @radaeze can you please approve?

Adding topics for management console upgrade and patch

---

console/console-index.html.md.erb
console/console-troubleshooting.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/ova-deployment-prereqs.html.md.erb
console/upgrade-console.html.md.erb

Updated supported versions of NSX-T for Gear 2.

Updated NSX-T support and other small edits in Console doc

---

understanding-upgrades.html.md.erb

Authored-by: Todd Sedano <tsedano@pivotal.io>

Adds that k8s will be upgraded when a cluster is upgraded

---

release-notes.html.md.erb

Please merge and publish to prod. Thank you.

Adding KB article link

---

nsxt-deploy.html.md.erb
pks-install-nsxt.html.md.erb

Fix ref to missing file

---

bbr-backup.html.md.erb

Please backport to 1.2, 1.3 and 1.4.

Fix instructions on how to use a jumbox for BBR

---

vsphere-nsxt-om-deploy.html.md.erb

Address feedback from the field re: SSH key requirements for Ops Manager v2.6

Update Ops Manager installation

---

nsxt-generate-pi-cert.html.md.erb

Update to this topic

---

installing-nsx-t.html.md.erb
nsxt-install-config-steps.html.md.erb
nsxt-install-create-t0.html.md.erb

Adding a feature that was added in 1.4 (and in the 1.4 docs) but is not in the 1.5 docs. t

Update nsxt install

---

network-profiles-define.html.md.erb
network-profiles-dns.html.md.erb
network-profiles-edge.html.md.erb
network-profiles-fip.html.md.erb
network-profiles-index.html.md.erb
network-profiles-lb-size.html.md.erb
network-profiles-ncp.html.md.erb
network-profiles-nodes.html.md.erb
network-profiles-ns-groups.html.md.erb
network-profiles-pods.html.md.erb
nsxt-service-mesh.html.md.erb

This PR refactors the network profile documentation and adds new network profile features for 1.5: DNS lookup and NCP configuration.

Config ncp

---

release-notes.html.md.erb

Also, see https://github.com/pivotal-cf/docs-pks/pull/721.

Improve release notes for BBR PKS security issue

---

create-sinks.html.md.erb
release-notes.html.md.erb

These changes include
1. Sink -> LogSink
1. ClusterSink -> ClusterLogSink
1. apps.pivotal.io -> pksapi.io

Document breaking sink name changes in 1.5

---

nsxt-install-edge-node-install.html.md.erb

Fix link to graphic

---

network-profiles-define.html.md.erb

Updates to network profile docuentations

---

network-profiles-define.html.md.erb
network-profiles-index.html.md.erb
network-profiles-lb-size.html.md.erb
network-profiles-ncp.html.md.erb

Updates to the new net profile features for 1.5

---

create-sinks.html.md.erb

Adds versioning to the links for telegraf

Versions for telegraf

---

create-sinks.html.md.erb
release-notes.html.md.erb

This commit also includes changes for
1. Adding the metric sink resource
1. Adding deprecation notice for pks-cli
1. Adding additional details to release notes.

adds details about the metricsink resource

---

nsx-sm.html.md.erb
nsxt-install-verify-pks.html.md.erb

Verify install nsxt

---

create-cluster.html.md.erb
view-cluster-details.html.md.erb

Adding cluster --details and pre-provision IP

---

console/console-index.html.md.erb
console/console-troubleshooting.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/monitor-manage-console.html.md.erb
console/patch-console-components.html.md.erb
console/upgrade-console.html.md.erb

Another wave of tech review on the Management Console docs, mostly related to the deployment wizard. More to follow....

Technical review feedback on Management Console docs

---

release-notes.html.md.erb

Updated new features list and product snapshot to add Management Console.
@animatedmax can you please approve & merge? Thanks!

Adding Management Console info to release notes

---

console/console-troubleshooting.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/monitor-manage-console.html.md.erb

Changed Kubernetes UI to Kubernetes Dashboard

Management Console doc updates following UI changes

---

console/console-identity-management.html.md.erb
console/console-login-opsmanager.html.md.erb
console/console-troubleshooting.html.md.erb
console/delete-console-deployment.html.md.erb
console/monitor-manage-console.html.md.erb
console/ova-deployment-prereqs.html.md.erb
console/patch-console-components.html.md.erb
console/reconfigure-console.html.md.erb
console/upgrade-console.html.md.erb

@animatedmax can you please approve and merge?

More tech review and content reorg for management console

---

console/deploy-ent-pks-yaml.html.md.erb

@animatedmax sorry I missed this in the previous PR. Please can you merge? Thanks!

Added table of YAML networking options for console

---

console/delete-console-deployment.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/ova-deployment-prereqs.html.md.erb

Sorry to keep bombarding you, @animatedmax, but here's another one for console...

Restored some changes accidentally overwritten

---

checklist.html.md.erb

az cli role subgroup incorrect

---

console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/ova-deployment-prereqs.html.md.erb
release-notes.html.md.erb

Some last minute changes to the management console docs. @animatedmax can you please approve/merge? Thanks!

Comments from Vui on Console

---

console/console-login-opsmanager.html.md.erb

@animatedmax can you please approve and merge? Thanks!

Corrected OpsMan login username

---

release-notes.html.md.erb

Created a distinct snapshot table per request from @vikafed. @vikafed is this OK?

Moved management console snapshot into a separate table in release notes

---

release-notes.html.md.erb

@animatedmax can you please approve and merge? Thanks!

Removed console known issues from RN and added new ones

---

release-notes.html.md.erb

Can we please merge this and put it on staging for PM review? It's needs review before pushing to prod. Thanks.

Adding back support for nsx-t 2.4.2 with caveat

---

troubleshoot-issues.html.md.erb

https://www.pivotaltracker.com/story/show/168089110

Add warning message regarding node drain options

---

troubleshoot-issues.html.md.erb

https://www.pivotaltracker.com/story/show/168089110

Add node exporter to drain warning

---

shutdown-startup.html.md.erb

Update from feedback

---

network-profiles-dns.html.md.erb

More updates. Please make available on staging. Thank you.

Updates from PM feedback

---

network-profiles-ncp-logerr.html.md.erb

Part of the staging site until we push out tomorrow.

Remove drop logged traffic, not supported in 1.5

---

network-profiles-shared-t1.html.md.erb
release-notes.html.md.erb

Please merge for staging. Thank you.

Updating 1.5 RNs with support for NSX-T v2.5

---

release-notes.html.md.erb

Fix link and wording

---

troubleshoot-issues.html.md.erb

https://pivotal-spike.atlassian.net/browse/PKS-380

Address issue pks-380

---

nsxt-generate-ca-cert.html.md.erb

CSR file for VIP has entry DNS.1 instead of DNS.1 = IP-ADDRESS

Fixed the Documentation Issue in the CSR file

---

console/console-index.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/ova-deployment-prereqs.html.md.erb

@animatedmax this is the first wave of updates for the gear2 1.5.1 GA release. Is this the correct branch? Thanks!

First wave of updates for Gear2 GA

---

console/deploy-ent-pks-wizard.html.md.erb

Tested deployment docs against 1.5.1 UI and adjusted accordingly.

Adjusted gear2 docs with 1.5.1 UI updates

---

console/patch-console-components.html.md.erb
console/upgrade-console.html.md.erb

Minor updates to upgrade and patching procedures for 1.5.1

Updating gear2 patch and upgrade docs for 1.5.1

---

console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/patch-console-components.html.md.erb
console/upgrade-console.html.md.erb

Reinstated note about upgrading/patching from beta.

More Gear 2 1.5.1 GA updates

---

console/deploy-console-ova.html.md.erb

Still trying to fix my nesting...

Yet more formatting fixes

---

console/console-index.html.md.erb
console/deploy-console-ova.html.md.erb
console/deploy-ent-pks-wizard.html.md.erb
console/deploy-ent-pks-yaml.html.md.erb
console/ova-deployment-prereqs.html.md.erb
console/prereqs-flannel.html.md.erb
console/prereqs-nsxt-automatednat.html.md.erb
console/prereqs-nsxt-byot.html.md.erb
console/prereqs-vsphere.html.md.erb

New content for Gear 2 1.5.1 GA, based on suggestions by @lparis and changes to the UI

Gear 2 GA updates based on UI changes

---

release-notes.html.md.erb

https://pivotal-spike.atlassian.net/browse/PKS-408

Address PKS JIRA issue PKS-408

---

release-notes.html.md.erb

https://pivotal-spike.atlassian.net/browse/PKS-349

Address PKS JIRA PKS-349

---

telemetry.html.md.erb

Telemetry docs related changes

Add links to sample workbook, tableau reader, and interpretation guide Telemetry docs

---

network-profiles-define.html.md.erb

This applies to 1.5 and 1.6 branches. Thanks.

Add source_ip for persistence

---

nsxt-multi-t0.html.md.erb
vsphere-host-group.html.md.erb

Important fixes please. Thanks.

Remove stretch cluser other fixes

---

telemetry.html.md.erb

Story Reference here: [#169022434](https://www.pivotaltracker.com/story/show/169022434)

Update Telemetry Data Dictionary link to point to 1.6 tab

---

troubleshoot-issues.html.md.erb

because the command has been fixed per eng and pm

Remove troubleshooting tip when delete-cluster fails 

---

create-sinks.html.md.erb

PKS 1.5 has 1.11.0 and 1.12 of telegraf installed, linking to older docs for compatibility

Update telegraf docs link to installed version

---

create-sinks.html.md.erb

Missed one! 
https://www.pivotaltracker.com/story/show/169236607

Update output plugins link to correct version of telegraf

---

network-profiles-ncp-logerr.html.md.erb

Adding error handling for network profile for 1.6

Adding error handling net profile option for 1.6

---

network-profiles-define.html.md.erb

Updates to Network Profile definition for 1.6

Updating net prof definition for 1.6

---

release-notes.html.md.erb

Adding [BETA X] reference to the feature list per request from Anish.

Update 1.6 RNs to include BETA 1 for features that are in beta.

---

nsxt-health.html.md.erb
nsxt-https-redirect.html.md.erb
nsxt-ingress-scale.html.md.erb
nsxt-ingress.html.md.erb

Will need some polish, which I will do later today/tomorrow AM. OK to merge now for review. Thanks.

16 networking features

---

docker-custom-ca-certs.html.md.erb

[#169235660]
Co-authored-by: Ramya Shenoy <rshenoy@pivotal.io>
Co-authored-by: Shyam Sankaran <ssankaran@pivotal.io>

Adding improvements to custom ssl ca certs documentation

---

nsxt-https-redirect.html.md.erb
nsxt-ingress-rewrite-url.html.md.erb

Please merge this and I will remove it in another PR based on the Go-No Go meeting today for 1.6.

Updates to https-redirect

---

cli/index.html.md.erb

Customer are asking we should give more example of how to login with SSO flag if tile is configured with SAML

Add example if login of SSO flag

---

upgrade-pks-nsxt.html.md.erb
upgrade-pks.html.md.erb
vsphere-index.html.md.erb
vsphere-nsxt-index.html.md.erb

Adding links to the console docs from the topics on installing/upgrading on vSphere.
cc @lparis FYI

Linking to console from standard vSphere docs

---

release-notes.html.md.erb

Added Management Console 1.5.2 release notes, and grouped all MC content together to match the 1.6 and 1.7 RNs.
**PLEASE DO NOT PUBLISH UNTIL 1.5.2 IS RELEASED**

Updated release notes for EPMC 1.5.2

---

k8s-profiles.html.md.erb

Fixes the flag name kubernetes-profile for cluster creation and update commands

Update flag name for kubernetes profile

---

create-sinks.html.md.erb

- Link to telegraf 1.13.4 documentation
- Link to fluent-bit 1.3.x documentation

Update links to sink-resources components

---

console/network-profile-console.html.md.erb

Updates to console network profile from review

---

okta-sso-config.html.md.erb

Fix the way graphics are referenced in this file

---

console/prereqs-nsxt-byot.html.md.erb

Fixed the NSX-T BYOT prereqs for 1.7, following change in requirements.

NSX-T fix in console docs

---

release-notes.html.md.erb

Added RN section for TKGIMC 1.8.1 and added a new known issue

Added RN section for TKGIMC 1.8.1 and added a new known issueAdded RN

---

nsxt-prepare-env.html.md.erb

https://github.com/pivotal-cf/docs-pks/issues/1179

Address Issue #1179

---

create-sinks.html.md.erb

[#174825877]
Signed-off-by: Louie Brann <lbrann@vmware.com>

1.7 - sinks documentation: Add section about when to use MetricSink vs ClusterMetricSink

---

create-sinks.html.md.erb

[#174825877]
Signed-off-by: Louie Brann <lbrann@vmware.com>

1.8 - sinks documentation: Add section about when to use MetricSink vs Cluster

---

nsxt-3-0-install.html.md.erb

That could be merged to branch 1.8 as well

Simplify the NSX-T VIP certificate generation

---

volumes.html.md.erb

added missing indentiation

---

azure-api-load-balancer.html.md.erb

1.8 - 1.10
Refactor the document of Azure LB for TKGI API

Refactor the azure lb doc

---

azure-api-load-balancer.html.md.erb

1.8 to 1.10
- Add back backend pool description
- refactor name

Add back backend pool description

---

release-notes.html.md.erb

Added TKGIMC NSXT cert issue to 1.8 RNs

---

release-notes.html.md.erb

Added TKGIMC NSX-T cert issue to 1.7 RNs

---

release-notes.html.md.erb

Removed dup Features section for MC
