pivotal-cf/docs-pks

installing-pks-aws.html.md.erb
installing-pks-gcp.html.md.erb
installing-pks-vsphere.html.md.erb

- If customers experience slowness with calls to the PKS API, or if
requests to the PKS API are timing out, they should scale up the
on-demand broker job under 'Resource Config'.
[#156997552]

Suggest increasing on-demand broker job resources

---

deploy-workloads.html.md.erb

Seems like the public subnet keywords got dropped. Adding them back in

Add back important "public subnet" context

---

installing-pks.html.md.erb
release-notes.html.md.erb
vsphere-prepare-env.html.md.erb

- For 1.1, the user will no longer need to configure the vSphere worker
credentials, resolving a high severity security issue.
[#157813130]

Remove vSphere worker credentials

---

installing-pks.html.md.erb
release-notes.html.md.erb

We also were not sure if we should note somewhere in the docs now that RBAC is default for all clusters, as we removed the selector in the tile.
[#157803176]
Signed-off-by: Angela Chin <achin@pivotal.io>

Update docs to note ABAC removal in 1.1

---

configure-api.html.md.erb

The property name for the PKS UAA admin client credentials in PKS 1.1.0 changed from "Uaa Admin Secret" to "Pks Uaa Management Admin Client".

Changed location of UAA admin creds for PKS 1.1.0

---

gcp-prepare-env.html.md.erb
installing-pks.html.md.erb

+ The service account key is no longer required, only the email
associated with the service account.
[#156880686]
Signed-off-by: Neil Hickey <nhickey@pivotal.io>

Cloud provider for GCP updated to ask for service account name

---

gcp-api-load-balancer.html.md.erb
installing-pks.html.md.erb

+ when configuring a LB, it now points to the resource config section
where an operator would input the LB name in the tile
[#158179643]

Update the PKS API Load Balancer documentation to be more clear

---

gcp-prepare-env.html.md.erb

In pks 1.1.x is not going to be more necessary to add the JSON key when setting up the cloud provider. Only the service account id is going to be necessary. 
This part of the documentation can be removed because not more necessary. 
[#158457770]

Remove outdated information about downloading json for gcp accounts

---

installing-pks.html.md.erb

- remains consistent with the property renaming in the tile
[#158457879]

Rename GCP service account to ID

---

manage-users.html.md.erb

* there are two uaa servers in the deployment, one on the opsman and the uaa server on the pks api instance
* the user should target the uaa running on the pks api instance

clarifies the location of UAA for pks-cli

---

installing-nsx-t.html.md.erb

Clarifies that the DNS common name (FQDN) is required with the NSX Manager cert, and adds example. Reported by VMW Support. See https://jira.eng.vmware.com/browse/PKS-896.

Addresses PKS-896: doc ex for NSX Mgr Cert must specify the SAN

---

installing-nsx-t.html.md.erb

@mjgutermuth This addresses an issue pointed out by EMC staff (by way of VMW TPM) who were installing PKS to support multiple Kubernetes clusters. Let me know if I've got it in the right spot, and if it makes sense. thanks

Updating Nodes IP Block size recommendation for PKS with NSX-T installs

---

installing-pks.html.md.erb

Instead of linking the generic Wavefront doc site, we should link directly to their PKS page.

Link directly to Wavefront PKS Documentation

---

vsphere-requirements.html.md.erb

@mjgutermuth @vikafed Per Anish we need to remove vSphere 6.5 U2 from the support matrix. Thanks.

PKS 1.1 does not support vSphere 6.5 U2, removing

---

release-notes.html.md.erb

@mjgutermuth Adds the compatible software versions for NSX-T and NCP to the Product Snapshot section of the PKS 1.1 release notes. Based on feedback from VMW field eng. thanks

Adding to RNs compatible versions for NSX-T and NCP

---

upgrading.html.md.erb

For now it is the same as the actual page title, but perhaps we name it in such a way that distinguishes between NSX-T upgrades and PKS tile upgrades.

Should make the distinction with PKS tile

---

generate-certificates.html.md.erb

Critical fixes to this doc page: https://docs.pivotal.io/runtimes/pks/1-1/generate-certificates.html#certificates-super-user. Will need to be added to 1.2/Master branch as well.

Fixes two issues with nsxt cert commands

---

aws-api-load-balancer.html.md.erb
aws-prepare-env.html.md.erb

update to create role instead of user for instance profile
Add documentation to point DNS to load balancer
When describing how to point a dns entry to the load balancer address there are 2 options depending on customer handling of dns. We added them as _Step 2, Option 1_ and _Step 2, Option 2_.  We are not sure what is the best or accepted way of presenting this kind of possibilities. Please restructure as necessary.
[#159326026]

Change docs to create a classical load balancer

---

nsxt-prepare-env.html.md.erb

Reported via Slack: "ls-pks-service is not required since PKS will automate the creation/deletion of cluster networking. i.e. for each k8s cluster, a NSX-T logical network will be created. so you can skip the creation of ls-pks-service."

Remove manual logical switch for service network, no longer needed

---

gcp-cluster-load-balancer.html.md.erb

[#160788658]
We noticed that we were missing a final step in the LB configuration.

Added final step on configuring LB for GCP

---

manage-users.html.md.erb

They should look like, I removed the html entities but I don't know if it's enough
```
kind: ROLE-TYPE
apiVersion: rbac.authorization.k8s.io/v1
metadata:
namespace: NAMESPACE
name: ROLE-OR-CLUSTER-ROLE-NAME
rules:
- apiGroups:
resources: RESOURCE
verbs: API-REQUEST-VERB
```
```
kind: ROLE-BINDING-TYPE
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: ROLE-OR-CLUSTER-ROLE-BINDING-NAME
namespace: NAMESPACE
subjects:
- kind: User
name: USERNAME
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: ROLE-TYPE
name: ROLE-OR-CLUSTER-ROLE-BINDING-NAME
apiGroup: rbac.authorization.k8s.io
```

Fix indentation

---

manage-users.html.md.erb

```
curl 'https://PKS-API>:8443/oauth/token' -k -XPOST -H 
'Accept: \application/json' -d "client_id= 
pks_cluster_client&client_secret=""&grant_type=password
&username=UAA-USERNAME&password=UAA-PASSWORD&response_type=id_token"
```
should be
```
curl 'https://PKS-API>:8443/oauth/token' -k -XPOST -H 
'Accept: application/json' -d "client_id= 
pks_cluster_client&client_secret=""&grant_type=password
&username=UAA-USERNAME&password=UAA-PASSWORD&response_type=id_token"
```

manage-users page curl command Header typo

---

installing-nsx-t.html.md.erb

The wording for the Service Network field was inaccurate, as since somewhere in PKS 1.1.x, service networks are all created on-demand for new k8s clusters as they are being provisioned. They are *not* created during tile installation, as the existing wording implies.
Added some clarifying words to the line below also, since it was not clear that in an upgrade scenario, it will place existing service instances on this network because in older versions, networks were not created for each k8s cluster at provisioning time, they were all in one network.

Update wording for Service Network field

---

release-notes.html.md.erb
upgrade-pks-nsxt.html.md.erb

Updates RNs and NSX-T upgrade sections to indicate PKS 1.2.x supports NSX-T 2.3. Please hold off on merging until the word is official. thanks

Update docs to indicate support for NSX-T 2.3

---

create-cluster.html.md.erb

When creating a cluster using the example command provided, the experience in the CLI does not communicate the expected time needed for cluster creation. By providing this "note", we can set an expectation that this _could_ take up to 30 minutes (this time duration was informed by a conversation with the developers on the team).

Set an expectation about cluster creation time

---

generate-nsx-pi-cert.html.md.erb

Addresses formatting issue here: https://docs.pivotal.io/runtimes/pks/1-2/generate-nsx-pi-cert.html#certificate-super-user-ui.
Step 4 script displays as "pem_encoded": "$(awk '{printf "%s\n", $0}' $NSX_SUPERUSER_CERT_FILE)" when it should be "%s\\\n"   (it needs to show 1 more ‘\’ as per the source). The way it displays in Option B is correct.
Fixed the other one (although not causing a problem) for consistency. 
Should also go into Master.

Fix formatting for script element

---

installing-pks-vsphere.html.md.erb
release-notes.html.md.erb

Added wildcard information for the no-proxy property. including the fact that some  jobs accept `*.` as wildcard and some others `.` to prefix domains with wildcards.
Perhaps we should recommend to type both in case the user is not sure? Example: always type `*.foo.bar` and `.foo.bar` if you want to have a wildcard for `whatever.foo.bar`
Signed-off-by: Greg Patricio <gpatricio@pivotal.io>

Update info on no-proxy property with wildcards

---

gcp-api-load-balancer.html.md.erb

When configuring the frontend for the LB on GCP the latest version of the console only allows a single port or a range to be specified. Each IP-port must be separately mapped.

Frontend config only allows single port or range

---

aws-requirements.html.md.erb
gcp-requirements.html.md.erb
vsphere-nsxt-requirements.html.md.erb
vsphere-requirements.html.md.erb

Addresses doc bug sent to me via email. BOSH Director VM needs to be included in the list of VMs that get deployed as part of PKS. 
This PR also applies to the Master branch.
thanks

Adding BOSH Director VM to requirements for all IaaS's

---

release-notes.html.md.erb

Docker is part of CFCR: https://docs-cfcr.cfapps.io/overview/release-notes/
PKS packages CFCR. The latest release of Docker supported by CFCR  is 17.12.1-ce (CFCR v0.24.0).

Add docker v to 1.2 rns

---

release-notes.html.md.erb

The docker component is managed by the CFCR team via the docker-boshrelease component: https://github.com/cloudfoundry-incubator/docker-boshrelease/. PKS 1.3 will be shipped with Docker v18.06.1-ce.

Add docker version to RNs for 1.3

---

vsphere-persistent-storage.html.md.erb

The section Multiple vSphere Compute Clusters with Shared vSAN Datastores was incorrectly named/described and did not match its actual diagram which was correct and would in-fact allow dynamic PVs to work, as the table higher up on the same page actually described.
Fixed the section name, fixed the language, removed the warning that this topology does not work with persistent volumes.
Secondly, "VMFS over NFS" is not an accurate phrase. NFS is NFS, which is separate to VMFS. 
Only FC/iSCSI use VMFS, while NFS is its own thing that vSphere also functions with, so I have corrected all instances of referring to NFS as a type of VMFS.

Fix vSAN w/ shared datastore case + NFS language

---

vsphere-persistent-storage.html.md.erb

Clarified that Static PV provisioning does work in 2 topologies, even though Dynamic does not. The diagrams already reflect this but the text did not.

Update warning on 2 topologies

---

release-notes.html.md.erb

Stemcell for 1.2.6 is 97.43 (https://github.com/pivotal-cf/p-pks-integrations/compare/v1.2.5-build.4...v1.2.6-build.2). NSX-T 2.3.1 is supported in 1.2.5 and 1.2.6 (https://docs.vmware.com/en/VMware-NSX-T-Data-Center/2.3.1/rn/VMware-NSX-T-Data-Center-231-Release-Notes.html).

Updates to 1.2.5 and 1.2.6 RNs

---

network-profiles-define.html.md.erb
network-profiles.html.md.erb

This PR reverts the pod_routable param value from "enabled" to "true" because the change in the code was never actually merged, it was only shown that way during the TOI. Also, added some language to the Using Network Profiles topic to briefly explain what they are since the topic was split into two (this change is based on customer feedback). These updates apply to the 1.2 branch and the master branch. thanks

Updates to network profiles documentation

---

installing-pks-azure.html.md.erb

This property is going to be ignored when installing PKS on azure.
The updated should be part of 1.3.x documentation
[#163231314]

public ip vm_extensions as ignored for azure

---

backup-and-restore.html.md.erb
bbr-backup-cluster.html.md.erb
bbr-restore-cluster.html.md.erb

Hi!
Platform Recovery team here. This PR adds documentation on limitations about backup and restore of single master clusters. We also modified the main page of the backup restore to add links to newly created pages.
Thanks!
@pivotal-cf/pcf-backup-and-restore

Document limitations about backup&restore pks clusters

---

proxies.html.md.erb

PKS 1.3 accepts * as a no_proxy field

---

index.html.md.erb

Addresses https://github.com/pivotal-cf/docs-pks/issues/523 for 1.1 branch.

Update table indicating support for Harbor

---

volumes.html.md.erb

Duplicate name so the link didn't work for "Provision Dynamic PVs for Use with PKS:" https://docs.pivotal.io/runtimes/pks/1-3/volumes.html#dynamic-pv-statefulsets. Should also apply to master/1.4. Thank you.

Fix anchor tag name

---

azure-om-config.html.md.erb

This is causing a problem for our consumption of the docs:
Wrong style of quotes. Changed to the use proper single quotes.
Also, the title is Azure but the first sentence says AWS. Fixed.
Applies to 1.3 branch as well.
Thanks

Fix quote style and first sentence

---

create-cluster.html.md.erb

applies to 1.3, 1.2, and 1.4/master branches, thanks

Adding warning about special chars in cluster name

---

nsxt-prepare-env.html.md.erb

Customer placed BOSH in 172.17.31.0/24 and could not deploy clusters. PKS mgmt plane subnet MUST not use 172.17.0.0/16 subnet.
Also applies to 1.2 and 1.4/master.

Add PKS mgmt plane node to reserved IPs list

---

gcp-cluster-load-balancer.html.md.erb

An operator following the steps on https://docs.pivotal.io/runtimes/pks/1-3/gcp-cluster-load-balancer.html would fail to access the cluster on step 4, since the firewall rules and the load balancer has not yet been configured.
Luis & @jhvhs

Rearrange the steps to reflect the correct workflow

---

bbr-backup-cluster.html.md.erb

Hey folks,
This PR updates the docs to instruct people to use the `--all-deployments` flag when backing up their cluster deployments on PKS.  This is the recommended way of doing this and should be present in `1.3` onwards.  So please port this to all versions `1.3` onwards!
Please remove this line in versions `1.4` onwards but keep for version `1.3`.
[* BBR can only back up a single-master cluster.](https://github.com/gmrodgers/docs-pks/blob/44d856856b69e6d23fad320d80970df5cc561616/bbr-backup-cluster.html.md.erb#L18)
We also wanted to change the subnav headings for backing up and restoring a cluster deployments, but we did not have access to the `docs-book-pks` repo.  If you could change the two headings as shown in the `git diff` below:
```diff
diff --git …
```

Pks bbr all deployments

---

upgrade-pks-nsxt.html.md.erb

Embedding this info in the docs is causing a lot of headaches. We need to refer to a single source of truth. Going forward, Anish will put upgrade paths info on PivNet, which will be copied to the RNs. Thanks.

Removing version info from doc

---

manage-users.html.md.erb

This doc currently leads users to another page which has not any more information about how to locate the ca cert.
If you look at the "advanced troubleshooting with the bosh cli" it starts much the same, with sshing onto the opsman, but it actually
tells you were to locate the certificate. If I followed these directions, I would have to a) follow link, b) follow second link, c) Realize I cannot curl endpoint for certificate until I have a bearer token for opsman. d) have to look up more documentation on how to get a bearer token, and re look up various credentials.
If you are already on the opsman there is no reason for this.
Possibly the page that it is linked to should include this information as well.

Add location of ca cert to documentation

---

aws-cluster-load-balancer.html.md.erb
create-cluster.html.md.erb
deploy-workloads.html.md.erb

The VMW conversion tool MD2HTML cannot process these reference paths. We have to fix them manually until this is merged. Also applies to the 1.4/master branch. Thanks. 
Invalid path in file: aws-cluster-load-balancer.html in text: ../about-lb.html
Invalid path in file: create-cluster.html in text: ../deploy-workloads.html
Invalid path in file: deploy-workloads.html in text: ../about-lb.html

Fixing ref paths so the topics render correctly in VMW MD2HTML tool

---

vsphere-nsxt-index.html.md.erb

Reverts pivotal-cf/docs-pks#635 because we have the target docs now thanks to @lparis

Revert "Revert "Adding fresh install docs for NSXT-2.4""

---

_create-auth-token-var.html.md.erb
resource-usage.html.md.erb

Most current commands fail due to formatting problems when you try to run them as is.
I amended those and included a couple more examples

Fixing Quota commands to allow copy&paste

---

_ssh-cluster-master-node.html.md.erb
diagnostic-tools.html.md.erb

After we could not find directions on how to SSH to the pks cluster nodes, we thought we'd contribute this PR. This is handy for debugging configuration of PKS issues, e.g. wanting to discover the kube-apiserver config.
Co-authored-by: Todd Sedano <tsedano@pivotal.io>
Co-authored-by: Zimeng Yang <zimengy@vmware.com>

Add directions for ssh to cluster master node

---

_vsphere_versions.html.md.erb
release-notes.html.md.erb

just point to the vmware interop matrix, restoring the partial in case someday we need it, but not referencing it anymore

Fixing the vsphere versions in the release notes

---

monitor-sinks.html.md.erb

In PKS 1.4 we improved the log format to use the human readable cluster name rather than the vm id. This reflects that change.

Human readable cluster names

---

release-notes.html.md.erb

Having `(recommended)` prior to the recommended version seem to be confusing to users. 
I believe it can be expressed better if the comment is placed after the version.

Update release notes to clarify NSX-T recommendation

---

gcp-cluster-load-balancer.html.md.erb

I was trying to use a PKS toolsmiths environment and I needed to
configure my load balancer. I found these steps to be super confusing.
https://docs.pivotal.io/runtimes/pks/1-4/gcp-cluster-load-balancer.html#backend
referred to
https://docs.pivotal.io/runtimes/pks/1-4/create-cluster.html#master-id
which referred to
https://docs.pivotal.io/pivotalcf/2-6/customizing/trouble-advanced.html
Yikes and too many levels of inception.
Since these directions are just for GCP, we can make them simpler
Authored-by: Todd Sedano <tsedano@pivotal.io>

Update gcp load balancer steps

---

bbr-backup.html.md.erb

It was referencing the director SSH key, rather than the jumpbox ssh key.
Thanks!
Jake & @alamages

Fix jumpbox key

---

bbr-backup.html.md.erb

Hey folks, we have added some more info to the BOSH_ALL_PROXY explanations, specifically:
- added ServerAliveInterval flag in manual ssh connection example
- version warning for potential timeouts for bbr <v1.5.1
- rearranged order of tunnel creation methods to subtly nudge users to
use the manual example
[#165377971]
Thanks,
Glen & @terminatingcode

Expanded on use of BOSH_ALL_PROXY

---

release-notes.html.md.erb

See this slack [thread](https://pivotal.slack.com/archives/C0554UNSS/p1560465440306600) for additional context.
Pending a fix from OM, we are flagging this as a release note since the current behavior is disconcerting to users upgrading PKS tiles.

Add known issue for Telemetry form 500 error

---

console/console-identity-management.html.md.erb
console/console-index.html.md.erb
release-notes.html.md.erb

Clarified how to identify LDAP/SAML provider. Replaced the "this is a beta" warning with hard-coded text, as it wasn't showing up correctly in the VMware version of the docs.
@animatedmax can you please merge?

Updated LDAP/SAML instructions and beta message

---

volumes.html.md.erb

When you create a StorageClass on vSphere, there is no need to specify:
- datastore
- diskformat
- fstype
The PKS tile is configured with defaults that you can use for the datastore, and kubectl contains defaults for the [others](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/storageclass.html). The person that configures the storageclass may not have any idea what a datastore is, or what it _might_ be named. Ditto for diskformat and fstype.
This change removes the over-complicated example.

Change StorageClass creation process

---

monitor-etcd.html.md.erb
sink-architecture.html.md.erb

This PR adds additional detail about the Node Exporter and how it works on both master and workers. It does not yet include changes to references in the install instructions (e.g. [GCP](https://docs.pivotal.io/pks/1-5/installing-pks-gcp.html))

Adds additional details about Node Exporter

---

create-sinks.html.md.erb

This PR covers two changes expected to be included in the 1.6 Beta tile build. These are
1. Removes the pks sink CLI commands. (We issued a deprecation warning last release)
1. Adds multiple output plugins for log sinks.

Sink changes for 1.6 beta

---

create-sinks.html.md.erb

Telegraf 1.9.3 is used on PKS 1.4, link to Metrics from that version in docs
https://www.pivotaltracker.com/story/show/169236607

Update telegraf docs link to installed version

---

release-notes.html.md.erb

I noticed that the staged RNs for PKS 1.6 include the info about Management Console 0.9. Updated to the 1.0.0 info.
I will update the RNs with 1.1 info once Console 1.1 is released.
**UPDATE**: Following discussion with @anishmehta1 and @lparis, we decided to completely comment out the Console sections until 1.1 is released.

Comment out the Management Console sections until 1.1 GA

---

release-notes.html.md.erb

The console content was suppressed, but links are still showing up in the sub-menu on the right:
This PR removes the console content completely.

Removing console from 1.6 RNs

---

bbr-backup.html.md.erb

This informs operators that they can run a clean-up operation prior to performing a BOSH director backup. It is accompanied by a warning note that this operation is destructive and to be aware of the potential damage.
Story [here](https://www.pivotaltracker.com/story/show/166407001)
cc @totherme

Add backup and restore recommendations

---

docker-custom-ca-certs.html.md.erb

Feedback received:
1) The authorization header which contains the token needs to be double quotes, not single. (Follow up with Lorenzo to correct docs)
2) Improve wording of https://docs.pivotal.io/pks/1-6/docker-custom-ca-certs.html#preparing-certificate as "\n" are added, not removed. (Follow up with Lorenzo)
3) FQDN for the private registry cannot contain a hyphen/single-dash "-" or a semi-colon (so can specify a port number) as the PKS API will reject it as not a valid character. Follow up with Lorenzo to update docs
This PR addresses #s 1 and 3. #2 I am not sure about since the purpose here is to remove the new lines chars so that the cert can be used on the command line. If the command we are providing is actually adding new line characters then we need to fix the command not the …

Feedback docker custom certs

---

console/console-ports-protocols.html.md.erb

Per comment from Vui via Slack: "just took a look at https://docs-pcf-staging.cfapps.io/pks-patches/1-6/console/console-ports-protocols.html, the last two rows (ideafarm-door and vami) we don't need"

Removed 2 rows from ports table

---

vsphere-host-group.html.md.erb

Remove stretched cluster from 1.6 docs. (It was already removed from 1.5 docs.)

Remove stretech cluster use case from host group

---

monitor-audit-logs.html.md.erb

This provides guidance for operators about using logs for performing security or other audits.  A few things to note. 
1. The content of this has been tracked as a need in [Aha](https://pcf.aha.io/features/KUBO-231), for a while and we iterated on a set of events in [this doc](https://docs.google.com/document/d/1lCVOjf_MWHUshOyLKKFRva3hqN2XptC84JcJ5qTz7oE/edit#). 
1. Syslog should probably have some configuration instructions outside of installation. 
1. The PKS API events should considered to be added to past versions as the log content hasn't changed. 
1. We should look into improving a data dictionary for the Kubernetes audit logs. 
1. These logs are all pretty unlikely to change much but if they do we'll have to keep this up to date. 
1. This is not actually linked up in the …

Adds page for using logs for auditing purposes

---

release-notes.html.md.erb

Created release notes for Management Console 1.6.0-rev.3. This a patch release that is independent of any PKS release. 
Please not merge until we know the GA date for Console 1.6.0-rev.3.
@pspinrad I also grouped all of the console info together, per your suggestion.

Added RNs for console 1.6.0-rev.3 and grouped all console info

---

manage-cluster-permissions.html.md.erb

The section in question, roleRef -> name, is referring to the Role or ClusterRole that you are binding with the RoleBinding or ClusterRoleBinding. The word 'BINDING' being in that name makes it look like you are trying to refer to a RoleBinding or ClusterRoleBinding instead, which is incorrect.

Removing incorrect and misleading 'Binding'

---

manage-cluster-permissions.html.md.erb

The sentence was obviously copy/pasted from above and is not correct. In the example we are not creating a Role or a ClusterRole, we are creating a RoleBinding or a ClusterRoleBinding and using it to bind a Role or ClusterRole to a Group.

Fixing a copy-paste

---

azure-managed-identities.html.md.erb

I needed to add specific LB read permissions as above otherwise exposing a K8s service of type LB failed with:
4m52s Warning SyncLoadBalancerFailed service/nginx-lbsvc Error syncing load balancer: failed to ensure load balancer: network.LoadBalancersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'redacted' with object id 'dredacted' does not have authorization to perform action 'Microsoft.Network/loadBalancers/read' over scope '/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials."

add specfic LB permission

---

cli/index.html.md.erb

Add information about `PKS_USER_PASSWORD` environment variable when using get-credentials command

Change get-credentials help message

---

gcp-api-load-balancer.html.md.erb

Which other branches should this be merged with (if any)? 1.8 to 1.10
No need to add tag manually to TKGI API VM since bosh will do that if LB is input in Resource Config when deploying TKGI tile, and apply the firewall rule to the VM automatically, also add TKGI-API VM to the target pool automatically.

Update gcp LB doc

---

vsphere-nsxt-om-config.html.md.erb

I guess all branches could need that change.
Background:
I spent a whole day of troubleshooting my environment because of this. Which is important here is, that you also need to add NSX-T CAs to this bundle. Also this field takes a PEM-Bundle and not only a single CA-Certificate.
In other steps of the installations you explicitly configure the NSX-T Certificates but this is NOT enough to let BOSH work properly. You also MUST specify the certificate here. Because of the explicit configuration in other steps one is not directly tempted to add the cert at that place.

specified CAs which must be included
